#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafiate
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desafiate")]
	public partial class DesafiateDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEventos(Eventos instance);
    partial void UpdateEventos(Eventos instance);
    partial void DeleteEventos(Eventos instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertPuntuaciones(Puntuaciones instance);
    partial void UpdatePuntuaciones(Puntuaciones instance);
    partial void DeletePuntuaciones(Puntuaciones instance);
    partial void InsertSesiones(Sesiones instance);
    partial void UpdateSesiones(Sesiones instance);
    partial void DeleteSesiones(Sesiones instance);
    partial void InsertLogros(Logros instance);
    partial void UpdateLogros(Logros instance);
    partial void DeleteLogros(Logros instance);
    #endregion
		
		public DesafiateDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DesafiateConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DesafiateDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DesafiateDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DesafiateDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DesafiateDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Eventos> Eventos
		{
			get
			{
				return this.GetTable<Eventos>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Puntuaciones> Puntuaciones
		{
			get
			{
				return this.GetTable<Puntuaciones>();
			}
		}
		
		public System.Data.Linq.Table<Sesiones> Sesiones
		{
			get
			{
				return this.GetTable<Sesiones>();
			}
		}
		
		public System.Data.Linq.Table<Logros> Logros
		{
			get
			{
				return this.GetTable<Logros>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Eventos")]
	public partial class Eventos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cEvento;
		
		private string _cDescripcion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncEventoChanging(string value);
    partial void OncEventoChanged();
    partial void OncDescripcionChanging(string value);
    partial void OncDescripcionChanged();
    #endregion
		
		public Eventos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cEvento", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cEvento
		{
			get
			{
				return this._cEvento;
			}
			set
			{
				if ((this._cEvento != value))
				{
					this.OncEventoChanging(value);
					this.SendPropertyChanging();
					this._cEvento = value;
					this.SendPropertyChanged("cEvento");
					this.OncEventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDescripcion", DbType="VarChar(255)")]
		public string cDescripcion
		{
			get
			{
				return this._cDescripcion;
			}
			set
			{
				if ((this._cDescripcion != value))
				{
					this.OncDescripcionChanging(value);
					this.SendPropertyChanging();
					this._cDescripcion = value;
					this.SendPropertyChanged("cDescripcion");
					this.OncDescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nIdUsuario;
		
		private string _cFacebookString;
		
		private string _cXmlProperties;
		
		private byte _nFlag;
		
		private EntitySet<Puntuaciones> _Puntuaciones;
		
		private EntitySet<Logros> _Logros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnIdUsuarioChanging(int value);
    partial void OnnIdUsuarioChanged();
    partial void OncFacebookStringChanging(string value);
    partial void OncFacebookStringChanged();
    partial void OncXmlPropertiesChanging(string value);
    partial void OncXmlPropertiesChanged();
    partial void OnnFlagChanging(byte value);
    partial void OnnFlagChanged();
    #endregion
		
		public Usuarios()
		{
			this._Puntuaciones = new EntitySet<Puntuaciones>(new Action<Puntuaciones>(this.attach_Puntuaciones), new Action<Puntuaciones>(this.detach_Puntuaciones));
			this._Logros = new EntitySet<Logros>(new Action<Logros>(this.attach_Logros), new Action<Logros>(this.detach_Logros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nIdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nIdUsuario
		{
			get
			{
				return this._nIdUsuario;
			}
			set
			{
				if ((this._nIdUsuario != value))
				{
					this.OnnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._nIdUsuario = value;
					this.SendPropertyChanged("nIdUsuario");
					this.OnnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cFacebookString", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cFacebookString
		{
			get
			{
				return this._cFacebookString;
			}
			set
			{
				if ((this._cFacebookString != value))
				{
					this.OncFacebookStringChanging(value);
					this.SendPropertyChanging();
					this._cFacebookString = value;
					this.SendPropertyChanged("cFacebookString");
					this.OncFacebookStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cXmlProperties", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string cXmlProperties
		{
			get
			{
				return this._cXmlProperties;
			}
			set
			{
				if ((this._cXmlProperties != value))
				{
					this.OncXmlPropertiesChanging(value);
					this.SendPropertyChanging();
					this._cXmlProperties = value;
					this.SendPropertyChanged("cXmlProperties");
					this.OncXmlPropertiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nFlag", DbType="TinyInt NOT NULL")]
		public byte nFlag
		{
			get
			{
				return this._nFlag;
			}
			set
			{
				if ((this._nFlag != value))
				{
					this.OnnFlagChanging(value);
					this.SendPropertyChanging();
					this._nFlag = value;
					this.SendPropertyChanged("nFlag");
					this.OnnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Puntuaciones", Storage="_Puntuaciones", ThisKey="nIdUsuario", OtherKey="nIdUsuario")]
		public EntitySet<Puntuaciones> Puntuaciones
		{
			get
			{
				return this._Puntuaciones;
			}
			set
			{
				this._Puntuaciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Logros", Storage="_Logros", ThisKey="nIdUsuario", OtherKey="nIdUsuario")]
		public EntitySet<Logros> Logros
		{
			get
			{
				return this._Logros;
			}
			set
			{
				this._Logros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Puntuaciones(Puntuaciones entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Puntuaciones(Puntuaciones entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_Logros(Logros entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Logros(Logros entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Puntuaciones")]
	public partial class Puntuaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nIdPuntuacion;
		
		private int _nIdUsuario;
		
		private string _cEvento;
		
		private int _nPuntuacion;
		
		private System.DateTime _dFecha;
		
		private byte _nFlag;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnIdPuntuacionChanging(int value);
    partial void OnnIdPuntuacionChanged();
    partial void OnnIdUsuarioChanging(int value);
    partial void OnnIdUsuarioChanged();
    partial void OncEventoChanging(string value);
    partial void OncEventoChanged();
    partial void OnnPuntuacionChanging(int value);
    partial void OnnPuntuacionChanged();
    partial void OndFechaChanging(System.DateTime value);
    partial void OndFechaChanged();
    partial void OnnFlagChanging(byte value);
    partial void OnnFlagChanged();
    #endregion
		
		public Puntuaciones()
		{
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nIdPuntuacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nIdPuntuacion
		{
			get
			{
				return this._nIdPuntuacion;
			}
			set
			{
				if ((this._nIdPuntuacion != value))
				{
					this.OnnIdPuntuacionChanging(value);
					this.SendPropertyChanging();
					this._nIdPuntuacion = value;
					this.SendPropertyChanged("nIdPuntuacion");
					this.OnnIdPuntuacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nIdUsuario", DbType="Int NOT NULL")]
		public int nIdUsuario
		{
			get
			{
				return this._nIdUsuario;
			}
			set
			{
				if ((this._nIdUsuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._nIdUsuario = value;
					this.SendPropertyChanged("nIdUsuario");
					this.OnnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cEvento", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cEvento
		{
			get
			{
				return this._cEvento;
			}
			set
			{
				if ((this._cEvento != value))
				{
					this.OncEventoChanging(value);
					this.SendPropertyChanging();
					this._cEvento = value;
					this.SendPropertyChanged("cEvento");
					this.OncEventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nPuntuacion", DbType="Int NOT NULL")]
		public int nPuntuacion
		{
			get
			{
				return this._nPuntuacion;
			}
			set
			{
				if ((this._nPuntuacion != value))
				{
					this.OnnPuntuacionChanging(value);
					this.SendPropertyChanging();
					this._nPuntuacion = value;
					this.SendPropertyChanged("nPuntuacion");
					this.OnnPuntuacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dFecha", DbType="DateTime NOT NULL")]
		public System.DateTime dFecha
		{
			get
			{
				return this._dFecha;
			}
			set
			{
				if ((this._dFecha != value))
				{
					this.OndFechaChanging(value);
					this.SendPropertyChanging();
					this._dFecha = value;
					this.SendPropertyChanged("dFecha");
					this.OndFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nFlag", DbType="TinyInt NOT NULL")]
		public byte nFlag
		{
			get
			{
				return this._nFlag;
			}
			set
			{
				if ((this._nFlag != value))
				{
					this.OnnFlagChanging(value);
					this.SendPropertyChanging();
					this._nFlag = value;
					this.SendPropertyChanged("nFlag");
					this.OnnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Puntuaciones", Storage="_Usuarios", ThisKey="nIdUsuario", OtherKey="nIdUsuario", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Puntuaciones.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Puntuaciones.Add(this);
						this._nIdUsuario = value.nIdUsuario;
					}
					else
					{
						this._nIdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sesiones")]
	public partial class Sesiones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _nIdSesion;
		
		private string _cIP;
		
		private string _cFacebookString;
		
		private System.DateTime _dStart;
		
		private System.DateTime _dKeep;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnIdSesionChanging(long value);
    partial void OnnIdSesionChanged();
    partial void OncIPChanging(string value);
    partial void OncIPChanged();
    partial void OncFacebookStringChanging(string value);
    partial void OncFacebookStringChanged();
    partial void OndStartChanging(System.DateTime value);
    partial void OndStartChanged();
    partial void OndKeepChanging(System.DateTime value);
    partial void OndKeepChanged();
    #endregion
		
		public Sesiones()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nIdSesion", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long nIdSesion
		{
			get
			{
				return this._nIdSesion;
			}
			set
			{
				if ((this._nIdSesion != value))
				{
					this.OnnIdSesionChanging(value);
					this.SendPropertyChanging();
					this._nIdSesion = value;
					this.SendPropertyChanged("nIdSesion");
					this.OnnIdSesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cIP", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string cIP
		{
			get
			{
				return this._cIP;
			}
			set
			{
				if ((this._cIP != value))
				{
					this.OncIPChanging(value);
					this.SendPropertyChanging();
					this._cIP = value;
					this.SendPropertyChanged("cIP");
					this.OncIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cFacebookString", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cFacebookString
		{
			get
			{
				return this._cFacebookString;
			}
			set
			{
				if ((this._cFacebookString != value))
				{
					this.OncFacebookStringChanging(value);
					this.SendPropertyChanging();
					this._cFacebookString = value;
					this.SendPropertyChanged("cFacebookString");
					this.OncFacebookStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dStart", DbType="DateTime NOT NULL")]
		public System.DateTime dStart
		{
			get
			{
				return this._dStart;
			}
			set
			{
				if ((this._dStart != value))
				{
					this.OndStartChanging(value);
					this.SendPropertyChanging();
					this._dStart = value;
					this.SendPropertyChanged("dStart");
					this.OndStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dKeep", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime dKeep
		{
			get
			{
				return this._dKeep;
			}
			set
			{
				if ((this._dKeep != value))
				{
					this.OndKeepChanging(value);
					this.SendPropertyChanging();
					this._dKeep = value;
					this.SendPropertyChanged("dKeep");
					this.OndKeepChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Logros")]
	public partial class Logros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nIdLogro;
		
		private int _nIdUsuario;
		
		private string _cEvento;
		
		private string _cLogro;
		
		private System.DateTime _dFecha;
		
		private byte _nFlag;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnIdLogroChanging(int value);
    partial void OnnIdLogroChanged();
    partial void OnnIdUsuarioChanging(int value);
    partial void OnnIdUsuarioChanged();
    partial void OncEventoChanging(string value);
    partial void OncEventoChanged();
    partial void OncLogroChanging(string value);
    partial void OncLogroChanged();
    partial void OndFechaChanging(System.DateTime value);
    partial void OndFechaChanged();
    partial void OnnFlagChanging(byte value);
    partial void OnnFlagChanged();
    #endregion
		
		public Logros()
		{
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nIdLogro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nIdLogro
		{
			get
			{
				return this._nIdLogro;
			}
			set
			{
				if ((this._nIdLogro != value))
				{
					this.OnnIdLogroChanging(value);
					this.SendPropertyChanging();
					this._nIdLogro = value;
					this.SendPropertyChanged("nIdLogro");
					this.OnnIdLogroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nIdUsuario", DbType="Int NOT NULL")]
		public int nIdUsuario
		{
			get
			{
				return this._nIdUsuario;
			}
			set
			{
				if ((this._nIdUsuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._nIdUsuario = value;
					this.SendPropertyChanged("nIdUsuario");
					this.OnnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cEvento", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cEvento
		{
			get
			{
				return this._cEvento;
			}
			set
			{
				if ((this._cEvento != value))
				{
					this.OncEventoChanging(value);
					this.SendPropertyChanging();
					this._cEvento = value;
					this.SendPropertyChanged("cEvento");
					this.OncEventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cLogro", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string cLogro
		{
			get
			{
				return this._cLogro;
			}
			set
			{
				if ((this._cLogro != value))
				{
					this.OncLogroChanging(value);
					this.SendPropertyChanging();
					this._cLogro = value;
					this.SendPropertyChanged("cLogro");
					this.OncLogroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dFecha", DbType="DateTime NOT NULL")]
		public System.DateTime dFecha
		{
			get
			{
				return this._dFecha;
			}
			set
			{
				if ((this._dFecha != value))
				{
					this.OndFechaChanging(value);
					this.SendPropertyChanging();
					this._dFecha = value;
					this.SendPropertyChanged("dFecha");
					this.OndFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nFlag", DbType="TinyInt NOT NULL")]
		public byte nFlag
		{
			get
			{
				return this._nFlag;
			}
			set
			{
				if ((this._nFlag != value))
				{
					this.OnnFlagChanging(value);
					this.SendPropertyChanging();
					this._nFlag = value;
					this.SendPropertyChanged("nFlag");
					this.OnnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Logros", Storage="_Usuarios", ThisKey="nIdUsuario", OtherKey="nIdUsuario", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Logros.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Logros.Add(this);
						this._nIdUsuario = value.nIdUsuario;
					}
					else
					{
						this._nIdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
