#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerServerV1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SoccerV1")]
	public partial class SoccerDataModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMatch(SoccerServerV1.BDDModel.Match instance);
    partial void UpdateMatch(SoccerServerV1.BDDModel.Match instance);
    partial void DeleteMatch(SoccerServerV1.BDDModel.Match instance);
    partial void InsertTrainingDefinition(SoccerServerV1.BDDModel.TrainingDefinition instance);
    partial void UpdateTrainingDefinition(SoccerServerV1.BDDModel.TrainingDefinition instance);
    partial void DeleteTrainingDefinition(SoccerServerV1.BDDModel.TrainingDefinition instance);
    partial void InsertMatchParticipation(SoccerServerV1.BDDModel.MatchParticipation instance);
    partial void UpdateMatchParticipation(SoccerServerV1.BDDModel.MatchParticipation instance);
    partial void DeleteMatchParticipation(SoccerServerV1.BDDModel.MatchParticipation instance);
    partial void InsertPendingTraining(SoccerServerV1.BDDModel.PendingTraining instance);
    partial void UpdatePendingTraining(SoccerServerV1.BDDModel.PendingTraining instance);
    partial void DeletePendingTraining(SoccerServerV1.BDDModel.PendingTraining instance);
    partial void InsertPlayer(SoccerServerV1.BDDModel.Player instance);
    partial void UpdatePlayer(SoccerServerV1.BDDModel.Player instance);
    partial void DeletePlayer(SoccerServerV1.BDDModel.Player instance);
    partial void InsertPredefinedSoccerPlayer(SoccerServerV1.BDDModel.PredefinedSoccerPlayer instance);
    partial void UpdatePredefinedSoccerPlayer(SoccerServerV1.BDDModel.PredefinedSoccerPlayer instance);
    partial void DeletePredefinedSoccerPlayer(SoccerServerV1.BDDModel.PredefinedSoccerPlayer instance);
    partial void InsertPredefinedTeam(SoccerServerV1.BDDModel.PredefinedTeam instance);
    partial void UpdatePredefinedTeam(SoccerServerV1.BDDModel.PredefinedTeam instance);
    partial void DeletePredefinedTeam(SoccerServerV1.BDDModel.PredefinedTeam instance);
    partial void InsertSession(SoccerServerV1.BDDModel.Session instance);
    partial void UpdateSession(SoccerServerV1.BDDModel.Session instance);
    partial void DeleteSession(SoccerServerV1.BDDModel.Session instance);
    partial void InsertSoccerPlayer(SoccerServerV1.BDDModel.SoccerPlayer instance);
    partial void UpdateSoccerPlayer(SoccerServerV1.BDDModel.SoccerPlayer instance);
    partial void DeleteSoccerPlayer(SoccerServerV1.BDDModel.SoccerPlayer instance);
    partial void InsertSpecialTrainingDefinition(SoccerServerV1.BDDModel.SpecialTrainingDefinition instance);
    partial void UpdateSpecialTrainingDefinition(SoccerServerV1.BDDModel.SpecialTrainingDefinition instance);
    partial void DeleteSpecialTrainingDefinition(SoccerServerV1.BDDModel.SpecialTrainingDefinition instance);
    partial void InsertSpecialTraining(SoccerServerV1.BDDModel.SpecialTraining instance);
    partial void UpdateSpecialTraining(SoccerServerV1.BDDModel.SpecialTraining instance);
    partial void DeleteSpecialTraining(SoccerServerV1.BDDModel.SpecialTraining instance);
    partial void InsertTeam(SoccerServerV1.BDDModel.Team instance);
    partial void UpdateTeam(SoccerServerV1.BDDModel.Team instance);
    partial void DeleteTeam(SoccerServerV1.BDDModel.Team instance);
    #endregion
		
		public SoccerDataModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SoccerV1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerDataModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerDataModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerDataModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerDataModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.Match> Matches
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.Match>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.TrainingDefinition> TrainingDefinitions
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.TrainingDefinition>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.MatchParticipation> MatchParticipations
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.MatchParticipation>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.PendingTraining> PendingTrainings
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.PendingTraining>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.Player> Players
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.Player>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.PredefinedSoccerPlayer> PredefinedSoccerPlayers
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.PredefinedSoccerPlayer>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.PredefinedTeam> PredefinedTeams
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.PredefinedTeam>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.Session> Sessions
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.Session>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.SoccerPlayer> SoccerPlayers
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.SoccerPlayer>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.SpecialTrainingDefinition> SpecialTrainingDefinitions
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.SpecialTrainingDefinition>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.SpecialTraining> SpecialTrainings
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.SpecialTraining>();
			}
		}
		
		public System.Data.Linq.Table<SoccerServerV1.BDDModel.Team> Teams
		{
			get
			{
				return this.GetTable<SoccerServerV1.BDDModel.Team>();
			}
		}
	}
}
namespace SoccerServerV1.BDDModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Matches")]
	public partial class Match : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MatchID;
		
		private System.DateTime _DateStarted;
		
		private System.Nullable<System.DateTime> _DateEnded;
		
		private System.Nullable<bool> _WasTooManyTimes;
		
		private System.Nullable<bool> _WasJust;
		
		private System.Nullable<bool> _WasAbandoned;
		
		private System.Nullable<bool> _WasAbandonedSameIP;
		
		private EntitySet<MatchParticipation> _MatchParticipations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatchIDChanging(int value);
    partial void OnMatchIDChanged();
    partial void OnDateStartedChanging(System.DateTime value);
    partial void OnDateStartedChanged();
    partial void OnDateEndedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEndedChanged();
    partial void OnWasTooManyTimesChanging(System.Nullable<bool> value);
    partial void OnWasTooManyTimesChanged();
    partial void OnWasJustChanging(System.Nullable<bool> value);
    partial void OnWasJustChanged();
    partial void OnWasAbandonedChanging(System.Nullable<bool> value);
    partial void OnWasAbandonedChanged();
    partial void OnWasAbandonedSameIPChanging(System.Nullable<bool> value);
    partial void OnWasAbandonedSameIPChanged();
    #endregion
		
		public Match()
		{
			this._MatchParticipations = new EntitySet<MatchParticipation>(new Action<MatchParticipation>(this.attach_MatchParticipations), new Action<MatchParticipation>(this.detach_MatchParticipations));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MatchID
		{
			get
			{
				return this._MatchID;
			}
			set
			{
				if ((this._MatchID != value))
				{
					this.OnMatchIDChanging(value);
					this.SendPropertyChanging();
					this._MatchID = value;
					this.SendPropertyChanged("MatchID");
					this.OnMatchIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateStarted", DbType="DateTime NOT NULL")]
		public System.DateTime DateStarted
		{
			get
			{
				return this._DateStarted;
			}
			set
			{
				if ((this._DateStarted != value))
				{
					this.OnDateStartedChanging(value);
					this.SendPropertyChanging();
					this._DateStarted = value;
					this.SendPropertyChanged("DateStarted");
					this.OnDateStartedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEnded", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEnded
		{
			get
			{
				return this._DateEnded;
			}
			set
			{
				if ((this._DateEnded != value))
				{
					this.OnDateEndedChanging(value);
					this.SendPropertyChanging();
					this._DateEnded = value;
					this.SendPropertyChanged("DateEnded");
					this.OnDateEndedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WasTooManyTimes", DbType="Bit")]
		public System.Nullable<bool> WasTooManyTimes
		{
			get
			{
				return this._WasTooManyTimes;
			}
			set
			{
				if ((this._WasTooManyTimes != value))
				{
					this.OnWasTooManyTimesChanging(value);
					this.SendPropertyChanging();
					this._WasTooManyTimes = value;
					this.SendPropertyChanged("WasTooManyTimes");
					this.OnWasTooManyTimesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WasJust", DbType="Bit")]
		public System.Nullable<bool> WasJust
		{
			get
			{
				return this._WasJust;
			}
			set
			{
				if ((this._WasJust != value))
				{
					this.OnWasJustChanging(value);
					this.SendPropertyChanging();
					this._WasJust = value;
					this.SendPropertyChanged("WasJust");
					this.OnWasJustChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WasAbandoned", DbType="Bit")]
		public System.Nullable<bool> WasAbandoned
		{
			get
			{
				return this._WasAbandoned;
			}
			set
			{
				if ((this._WasAbandoned != value))
				{
					this.OnWasAbandonedChanging(value);
					this.SendPropertyChanging();
					this._WasAbandoned = value;
					this.SendPropertyChanged("WasAbandoned");
					this.OnWasAbandonedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WasAbandonedSameIP", DbType="Bit")]
		public System.Nullable<bool> WasAbandonedSameIP
		{
			get
			{
				return this._WasAbandonedSameIP;
			}
			set
			{
				if ((this._WasAbandonedSameIP != value))
				{
					this.OnWasAbandonedSameIPChanging(value);
					this.SendPropertyChanging();
					this._WasAbandonedSameIP = value;
					this.SendPropertyChanged("WasAbandonedSameIP");
					this.OnWasAbandonedSameIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Match_MatchParticipation", Storage="_MatchParticipations", ThisKey="MatchID", OtherKey="MatchID")]
		public EntitySet<MatchParticipation> MatchParticipations
		{
			get
			{
				return this._MatchParticipations;
			}
			set
			{
				this._MatchParticipations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MatchParticipations(MatchParticipation entity)
		{
			this.SendPropertyChanging();
			entity.Match = this;
		}
		
		private void detach_MatchParticipations(MatchParticipation entity)
		{
			this.SendPropertyChanging();
			entity.Match = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrainingDefinitions")]
	public partial class TrainingDefinition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TrainingDefinitionID;
		
		private string _Name;
		
		private string _Description;
		
		private int _FitnessDelta;
		
		private int _Time;
		
		private EntitySet<PendingTraining> _PendingTrainings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTrainingDefinitionIDChanging(int value);
    partial void OnTrainingDefinitionIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnFitnessDeltaChanging(int value);
    partial void OnFitnessDeltaChanged();
    partial void OnTimeChanging(int value);
    partial void OnTimeChanged();
    #endregion
		
		public TrainingDefinition()
		{
			this._PendingTrainings = new EntitySet<PendingTraining>(new Action<PendingTraining>(this.attach_PendingTrainings), new Action<PendingTraining>(this.detach_PendingTrainings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainingDefinitionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TrainingDefinitionID
		{
			get
			{
				return this._TrainingDefinitionID;
			}
			set
			{
				if ((this._TrainingDefinitionID != value))
				{
					this.OnTrainingDefinitionIDChanging(value);
					this.SendPropertyChanging();
					this._TrainingDefinitionID = value;
					this.SendPropertyChanged("TrainingDefinitionID");
					this.OnTrainingDefinitionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FitnessDelta", DbType="Int NOT NULL")]
		public int FitnessDelta
		{
			get
			{
				return this._FitnessDelta;
			}
			set
			{
				if ((this._FitnessDelta != value))
				{
					this.OnFitnessDeltaChanging(value);
					this.SendPropertyChanging();
					this._FitnessDelta = value;
					this.SendPropertyChanged("FitnessDelta");
					this.OnFitnessDeltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="Int NOT NULL")]
		public int Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrainingDefinition_PendingTraining", Storage="_PendingTrainings", ThisKey="TrainingDefinitionID", OtherKey="TrainingDefinitionID")]
		public EntitySet<PendingTraining> PendingTrainings
		{
			get
			{
				return this._PendingTrainings;
			}
			set
			{
				this._PendingTrainings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PendingTrainings(PendingTraining entity)
		{
			this.SendPropertyChanging();
			entity.TrainingDefinition = this;
		}
		
		private void detach_PendingTrainings(PendingTraining entity)
		{
			this.SendPropertyChanging();
			entity.TrainingDefinition = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MatchParticipations")]
	public partial class MatchParticipation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MatchParticipationID;
		
		private int _MatchID;
		
		private int _TeamID;
		
		private bool _AsHome;
		
		private int _Goals;
		
		private int _TurnsPlayed;
		
		private EntityRef<Match> _Match;
		
		private EntityRef<Team> _Team;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatchParticipationIDChanging(int value);
    partial void OnMatchParticipationIDChanged();
    partial void OnMatchIDChanging(int value);
    partial void OnMatchIDChanged();
    partial void OnTeamIDChanging(int value);
    partial void OnTeamIDChanged();
    partial void OnAsHomeChanging(bool value);
    partial void OnAsHomeChanged();
    partial void OnGoalsChanging(int value);
    partial void OnGoalsChanged();
    partial void OnTurnsPlayedChanging(int value);
    partial void OnTurnsPlayedChanged();
    #endregion
		
		public MatchParticipation()
		{
			this._Match = default(EntityRef<Match>);
			this._Team = default(EntityRef<Team>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchParticipationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MatchParticipationID
		{
			get
			{
				return this._MatchParticipationID;
			}
			set
			{
				if ((this._MatchParticipationID != value))
				{
					this.OnMatchParticipationIDChanging(value);
					this.SendPropertyChanging();
					this._MatchParticipationID = value;
					this.SendPropertyChanged("MatchParticipationID");
					this.OnMatchParticipationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchID", DbType="Int NOT NULL")]
		public int MatchID
		{
			get
			{
				return this._MatchID;
			}
			set
			{
				if ((this._MatchID != value))
				{
					if (this._Match.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatchIDChanging(value);
					this.SendPropertyChanging();
					this._MatchID = value;
					this.SendPropertyChanged("MatchID");
					this.OnMatchIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamID", DbType="Int NOT NULL")]
		public int TeamID
		{
			get
			{
				return this._TeamID;
			}
			set
			{
				if ((this._TeamID != value))
				{
					if (this._Team.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTeamIDChanging(value);
					this.SendPropertyChanging();
					this._TeamID = value;
					this.SendPropertyChanged("TeamID");
					this.OnTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsHome", DbType="Bit NOT NULL")]
		public bool AsHome
		{
			get
			{
				return this._AsHome;
			}
			set
			{
				if ((this._AsHome != value))
				{
					this.OnAsHomeChanging(value);
					this.SendPropertyChanging();
					this._AsHome = value;
					this.SendPropertyChanged("AsHome");
					this.OnAsHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Goals", DbType="Int NOT NULL")]
		public int Goals
		{
			get
			{
				return this._Goals;
			}
			set
			{
				if ((this._Goals != value))
				{
					this.OnGoalsChanging(value);
					this.SendPropertyChanging();
					this._Goals = value;
					this.SendPropertyChanged("Goals");
					this.OnGoalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TurnsPlayed", DbType="Int NOT NULL")]
		public int TurnsPlayed
		{
			get
			{
				return this._TurnsPlayed;
			}
			set
			{
				if ((this._TurnsPlayed != value))
				{
					this.OnTurnsPlayedChanging(value);
					this.SendPropertyChanging();
					this._TurnsPlayed = value;
					this.SendPropertyChanged("TurnsPlayed");
					this.OnTurnsPlayedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Match_MatchParticipation", Storage="_Match", ThisKey="MatchID", OtherKey="MatchID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Match Match
		{
			get
			{
				return this._Match.Entity;
			}
			set
			{
				Match previousValue = this._Match.Entity;
				if (((previousValue != value) 
							|| (this._Match.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Match.Entity = null;
						previousValue.MatchParticipations.Remove(this);
					}
					this._Match.Entity = value;
					if ((value != null))
					{
						value.MatchParticipations.Add(this);
						this._MatchID = value.MatchID;
					}
					else
					{
						this._MatchID = default(int);
					}
					this.SendPropertyChanged("Match");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Team_MatchParticipation", Storage="_Team", ThisKey="TeamID", OtherKey="TeamID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Team Team
		{
			get
			{
				return this._Team.Entity;
			}
			set
			{
				Team previousValue = this._Team.Entity;
				if (((previousValue != value) 
							|| (this._Team.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Team.Entity = null;
						previousValue.MatchParticipations.Remove(this);
					}
					this._Team.Entity = value;
					if ((value != null))
					{
						value.MatchParticipations.Add(this);
						this._TeamID = value.TeamID;
					}
					else
					{
						this._TeamID = default(int);
					}
					this.SendPropertyChanged("Team");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PendingTrainings")]
	public partial class PendingTraining : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TeamID;
		
		private int _TrainingDefinitionID;
		
		private System.DateTime _TimeStart;
		
		private System.DateTime _TimeEnd;
		
		private EntityRef<TrainingDefinition> _TrainingDefinition;
		
		private EntityRef<Team> _Team;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeamIDChanging(int value);
    partial void OnTeamIDChanged();
    partial void OnTrainingDefinitionIDChanging(int value);
    partial void OnTrainingDefinitionIDChanged();
    partial void OnTimeStartChanging(System.DateTime value);
    partial void OnTimeStartChanged();
    partial void OnTimeEndChanging(System.DateTime value);
    partial void OnTimeEndChanged();
    #endregion
		
		public PendingTraining()
		{
			this._TrainingDefinition = default(EntityRef<TrainingDefinition>);
			this._Team = default(EntityRef<Team>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TeamID
		{
			get
			{
				return this._TeamID;
			}
			set
			{
				if ((this._TeamID != value))
				{
					if (this._Team.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTeamIDChanging(value);
					this.SendPropertyChanging();
					this._TeamID = value;
					this.SendPropertyChanged("TeamID");
					this.OnTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainingDefinitionID", DbType="Int NOT NULL")]
		public int TrainingDefinitionID
		{
			get
			{
				return this._TrainingDefinitionID;
			}
			set
			{
				if ((this._TrainingDefinitionID != value))
				{
					if (this._TrainingDefinition.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTrainingDefinitionIDChanging(value);
					this.SendPropertyChanging();
					this._TrainingDefinitionID = value;
					this.SendPropertyChanged("TrainingDefinitionID");
					this.OnTrainingDefinitionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStart", DbType="DateTime NOT NULL")]
		public System.DateTime TimeStart
		{
			get
			{
				return this._TimeStart;
			}
			set
			{
				if ((this._TimeStart != value))
				{
					this.OnTimeStartChanging(value);
					this.SendPropertyChanging();
					this._TimeStart = value;
					this.SendPropertyChanged("TimeStart");
					this.OnTimeStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEnd", DbType="DateTime NOT NULL")]
		public System.DateTime TimeEnd
		{
			get
			{
				return this._TimeEnd;
			}
			set
			{
				if ((this._TimeEnd != value))
				{
					this.OnTimeEndChanging(value);
					this.SendPropertyChanging();
					this._TimeEnd = value;
					this.SendPropertyChanged("TimeEnd");
					this.OnTimeEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrainingDefinition_PendingTraining", Storage="_TrainingDefinition", ThisKey="TrainingDefinitionID", OtherKey="TrainingDefinitionID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TrainingDefinition TrainingDefinition
		{
			get
			{
				return this._TrainingDefinition.Entity;
			}
			set
			{
				TrainingDefinition previousValue = this._TrainingDefinition.Entity;
				if (((previousValue != value) 
							|| (this._TrainingDefinition.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrainingDefinition.Entity = null;
						previousValue.PendingTrainings.Remove(this);
					}
					this._TrainingDefinition.Entity = value;
					if ((value != null))
					{
						value.PendingTrainings.Add(this);
						this._TrainingDefinitionID = value.TrainingDefinitionID;
					}
					else
					{
						this._TrainingDefinitionID = default(int);
					}
					this.SendPropertyChanged("TrainingDefinition");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Team_PendingTraining", Storage="_Team", ThisKey="TeamID", OtherKey="TeamID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Team Team
		{
			get
			{
				return this._Team.Entity;
			}
			set
			{
				Team previousValue = this._Team.Entity;
				if (((previousValue != value) 
							|| (this._Team.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Team.Entity = null;
						previousValue.PendingTraining = null;
					}
					this._Team.Entity = value;
					if ((value != null))
					{
						value.PendingTraining = this;
						this._TeamID = value.TeamID;
					}
					else
					{
						this._TeamID = default(int);
					}
					this.SendPropertyChanged("Team");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Players")]
	public partial class Player : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PlayerID;
		
		private string _Name;
		
		private string _Surname;
		
		private string _FacebookID;
		
		private System.DateTime _CreationDate;
		
		private bool _Liked;
		
		private EntitySet<Session> _Sessions;
		
		private EntityRef<Team> _Team;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPlayerIDChanging(int value);
    partial void OnPlayerIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnFacebookIDChanging(string value);
    partial void OnFacebookIDChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    partial void OnLikedChanging(bool value);
    partial void OnLikedChanged();
    #endregion
		
		public Player()
		{
			this._Sessions = new EntitySet<Session>(new Action<Session>(this.attach_Sessions), new Action<Session>(this.detach_Sessions));
			this._Team = default(EntityRef<Team>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlayerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PlayerID
		{
			get
			{
				return this._PlayerID;
			}
			set
			{
				if ((this._PlayerID != value))
				{
					this.OnPlayerIDChanging(value);
					this.SendPropertyChanging();
					this._PlayerID = value;
					this.SendPropertyChanged("PlayerID");
					this.OnPlayerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FacebookID
		{
			get
			{
				return this._FacebookID;
			}
			set
			{
				if ((this._FacebookID != value))
				{
					this.OnFacebookIDChanging(value);
					this.SendPropertyChanging();
					this._FacebookID = value;
					this.SendPropertyChanged("FacebookID");
					this.OnFacebookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liked", DbType="Bit NOT NULL")]
		public bool Liked
		{
			get
			{
				return this._Liked;
			}
			set
			{
				if ((this._Liked != value))
				{
					this.OnLikedChanging(value);
					this.SendPropertyChanging();
					this._Liked = value;
					this.SendPropertyChanged("Liked");
					this.OnLikedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Player_Session", Storage="_Sessions", ThisKey="PlayerID", OtherKey="PlayerID")]
		public EntitySet<Session> Sessions
		{
			get
			{
				return this._Sessions;
			}
			set
			{
				this._Sessions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Player_Team", Storage="_Team", ThisKey="PlayerID", OtherKey="TeamID", IsUnique=true, IsForeignKey=false)]
		public Team Team
		{
			get
			{
				return this._Team.Entity;
			}
			set
			{
				Team previousValue = this._Team.Entity;
				if (((previousValue != value) 
							|| (this._Team.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Team.Entity = null;
						previousValue.Player = null;
					}
					this._Team.Entity = value;
					if ((value != null))
					{
						value.Player = this;
					}
					this.SendPropertyChanged("Team");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sessions(Session entity)
		{
			this.SendPropertyChanging();
			entity.Player = this;
		}
		
		private void detach_Sessions(Session entity)
		{
			this.SendPropertyChanging();
			entity.Player = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PredefinedSoccerPlayers")]
	public partial class PredefinedSoccerPlayer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PredefinedSoccerPlayerID;
		
		private string _Name;
		
		private int _PredefinedTeamID;
		
		private int _Type;
		
		private bool _IsSubstitute;
		
		private int _Number;
		
		private EntityRef<PredefinedTeam> _PredefinedTeam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPredefinedSoccerPlayerIDChanging(int value);
    partial void OnPredefinedSoccerPlayerIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPredefinedTeamIDChanging(int value);
    partial void OnPredefinedTeamIDChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnIsSubstituteChanging(bool value);
    partial void OnIsSubstituteChanged();
    partial void OnNumberChanging(int value);
    partial void OnNumberChanged();
    #endregion
		
		public PredefinedSoccerPlayer()
		{
			this._PredefinedTeam = default(EntityRef<PredefinedTeam>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PredefinedSoccerPlayerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PredefinedSoccerPlayerID
		{
			get
			{
				return this._PredefinedSoccerPlayerID;
			}
			set
			{
				if ((this._PredefinedSoccerPlayerID != value))
				{
					this.OnPredefinedSoccerPlayerIDChanging(value);
					this.SendPropertyChanging();
					this._PredefinedSoccerPlayerID = value;
					this.SendPropertyChanged("PredefinedSoccerPlayerID");
					this.OnPredefinedSoccerPlayerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PredefinedTeamID", DbType="Int NOT NULL")]
		public int PredefinedTeamID
		{
			get
			{
				return this._PredefinedTeamID;
			}
			set
			{
				if ((this._PredefinedTeamID != value))
				{
					if (this._PredefinedTeam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPredefinedTeamIDChanging(value);
					this.SendPropertyChanging();
					this._PredefinedTeamID = value;
					this.SendPropertyChanged("PredefinedTeamID");
					this.OnPredefinedTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSubstitute", DbType="Bit NOT NULL")]
		public bool IsSubstitute
		{
			get
			{
				return this._IsSubstitute;
			}
			set
			{
				if ((this._IsSubstitute != value))
				{
					this.OnIsSubstituteChanging(value);
					this.SendPropertyChanging();
					this._IsSubstitute = value;
					this.SendPropertyChanged("IsSubstitute");
					this.OnIsSubstituteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int NOT NULL")]
		public int Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PredefinedTeam_PredefinedSoccerPlayer", Storage="_PredefinedTeam", ThisKey="PredefinedTeamID", OtherKey="PredefinedTeamID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public PredefinedTeam PredefinedTeam
		{
			get
			{
				return this._PredefinedTeam.Entity;
			}
			set
			{
				PredefinedTeam previousValue = this._PredefinedTeam.Entity;
				if (((previousValue != value) 
							|| (this._PredefinedTeam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PredefinedTeam.Entity = null;
						previousValue.PredefinedSoccerPlayers.Remove(this);
					}
					this._PredefinedTeam.Entity = value;
					if ((value != null))
					{
						value.PredefinedSoccerPlayers.Add(this);
						this._PredefinedTeamID = value.PredefinedTeamID;
					}
					else
					{
						this._PredefinedTeamID = default(int);
					}
					this.SendPropertyChanged("PredefinedTeam");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PredefinedTeams")]
	public partial class PredefinedTeam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PredefinedTeamID;
		
		private string _Name;
		
		private EntitySet<PredefinedSoccerPlayer> _PredefinedSoccerPlayers;
		
		private EntitySet<Team> _Teams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPredefinedTeamIDChanging(int value);
    partial void OnPredefinedTeamIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public PredefinedTeam()
		{
			this._PredefinedSoccerPlayers = new EntitySet<PredefinedSoccerPlayer>(new Action<PredefinedSoccerPlayer>(this.attach_PredefinedSoccerPlayers), new Action<PredefinedSoccerPlayer>(this.detach_PredefinedSoccerPlayers));
			this._Teams = new EntitySet<Team>(new Action<Team>(this.attach_Teams), new Action<Team>(this.detach_Teams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PredefinedTeamID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PredefinedTeamID
		{
			get
			{
				return this._PredefinedTeamID;
			}
			set
			{
				if ((this._PredefinedTeamID != value))
				{
					this.OnPredefinedTeamIDChanging(value);
					this.SendPropertyChanging();
					this._PredefinedTeamID = value;
					this.SendPropertyChanged("PredefinedTeamID");
					this.OnPredefinedTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PredefinedTeam_PredefinedSoccerPlayer", Storage="_PredefinedSoccerPlayers", ThisKey="PredefinedTeamID", OtherKey="PredefinedTeamID")]
		public EntitySet<PredefinedSoccerPlayer> PredefinedSoccerPlayers
		{
			get
			{
				return this._PredefinedSoccerPlayers;
			}
			set
			{
				this._PredefinedSoccerPlayers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PredefinedTeam_Team", Storage="_Teams", ThisKey="PredefinedTeamID", OtherKey="PredefinedTeamID")]
		public EntitySet<Team> Teams
		{
			get
			{
				return this._Teams;
			}
			set
			{
				this._Teams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PredefinedSoccerPlayers(PredefinedSoccerPlayer entity)
		{
			this.SendPropertyChanging();
			entity.PredefinedTeam = this;
		}
		
		private void detach_PredefinedSoccerPlayers(PredefinedSoccerPlayer entity)
		{
			this.SendPropertyChanging();
			entity.PredefinedTeam = null;
		}
		
		private void attach_Teams(Team entity)
		{
			this.SendPropertyChanging();
			entity.PredefinedTeam = this;
		}
		
		private void detach_Teams(Team entity)
		{
			this.SendPropertyChanging();
			entity.PredefinedTeam = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sessions")]
	public partial class Session : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SessionID;
		
		private int _PlayerID;
		
		private System.DateTime _CreationDate;
		
		private string _FacebookSession;
		
		private EntityRef<Player> _Player;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSessionIDChanging(int value);
    partial void OnSessionIDChanged();
    partial void OnPlayerIDChanging(int value);
    partial void OnPlayerIDChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    partial void OnFacebookSessionChanging(string value);
    partial void OnFacebookSessionChanged();
    #endregion
		
		public Session()
		{
			this._Player = default(EntityRef<Player>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SessionID
		{
			get
			{
				return this._SessionID;
			}
			set
			{
				if ((this._SessionID != value))
				{
					this.OnSessionIDChanging(value);
					this.SendPropertyChanging();
					this._SessionID = value;
					this.SendPropertyChanged("SessionID");
					this.OnSessionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlayerID", DbType="Int NOT NULL")]
		public int PlayerID
		{
			get
			{
				return this._PlayerID;
			}
			set
			{
				if ((this._PlayerID != value))
				{
					if (this._Player.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPlayerIDChanging(value);
					this.SendPropertyChanging();
					this._PlayerID = value;
					this.SendPropertyChanged("PlayerID");
					this.OnPlayerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookSession", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string FacebookSession
		{
			get
			{
				return this._FacebookSession;
			}
			set
			{
				if ((this._FacebookSession != value))
				{
					this.OnFacebookSessionChanging(value);
					this.SendPropertyChanging();
					this._FacebookSession = value;
					this.SendPropertyChanged("FacebookSession");
					this.OnFacebookSessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Player_Session", Storage="_Player", ThisKey="PlayerID", OtherKey="PlayerID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Player Player
		{
			get
			{
				return this._Player.Entity;
			}
			set
			{
				Player previousValue = this._Player.Entity;
				if (((previousValue != value) 
							|| (this._Player.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Player.Entity = null;
						previousValue.Sessions.Remove(this);
					}
					this._Player.Entity = value;
					if ((value != null))
					{
						value.Sessions.Add(this);
						this._PlayerID = value.PlayerID;
					}
					else
					{
						this._PlayerID = default(int);
					}
					this.SendPropertyChanged("Player");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoccerPlayers")]
	public partial class SoccerPlayer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoccerPlayerID;
		
		private int _TeamID;
		
		private string _Name;
		
		private int _Number;
		
		private int _Type;
		
		private int _FieldPosition;
		
		private int _Weight;
		
		private int _Sliding;
		
		private int _Power;
		
		private bool _IsInjured;
		
		private EntityRef<Team> _Team;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoccerPlayerIDChanging(int value);
    partial void OnSoccerPlayerIDChanged();
    partial void OnTeamIDChanging(int value);
    partial void OnTeamIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnNumberChanging(int value);
    partial void OnNumberChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnFieldPositionChanging(int value);
    partial void OnFieldPositionChanged();
    partial void OnWeightChanging(int value);
    partial void OnWeightChanged();
    partial void OnSlidingChanging(int value);
    partial void OnSlidingChanged();
    partial void OnPowerChanging(int value);
    partial void OnPowerChanged();
    partial void OnIsInjuredChanging(bool value);
    partial void OnIsInjuredChanged();
    #endregion
		
		public SoccerPlayer()
		{
			this._Team = default(EntityRef<Team>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoccerPlayerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SoccerPlayerID
		{
			get
			{
				return this._SoccerPlayerID;
			}
			set
			{
				if ((this._SoccerPlayerID != value))
				{
					this.OnSoccerPlayerIDChanging(value);
					this.SendPropertyChanging();
					this._SoccerPlayerID = value;
					this.SendPropertyChanged("SoccerPlayerID");
					this.OnSoccerPlayerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamID", DbType="Int NOT NULL")]
		public int TeamID
		{
			get
			{
				return this._TeamID;
			}
			set
			{
				if ((this._TeamID != value))
				{
					if (this._Team.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTeamIDChanging(value);
					this.SendPropertyChanging();
					this._TeamID = value;
					this.SendPropertyChanged("TeamID");
					this.OnTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int NOT NULL")]
		public int Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldPosition", DbType="Int NOT NULL")]
		public int FieldPosition
		{
			get
			{
				return this._FieldPosition;
			}
			set
			{
				if ((this._FieldPosition != value))
				{
					this.OnFieldPositionChanging(value);
					this.SendPropertyChanging();
					this._FieldPosition = value;
					this.SendPropertyChanged("FieldPosition");
					this.OnFieldPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int NOT NULL")]
		public int Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sliding", DbType="Int NOT NULL")]
		public int Sliding
		{
			get
			{
				return this._Sliding;
			}
			set
			{
				if ((this._Sliding != value))
				{
					this.OnSlidingChanging(value);
					this.SendPropertyChanging();
					this._Sliding = value;
					this.SendPropertyChanged("Sliding");
					this.OnSlidingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Power", DbType="Int NOT NULL")]
		public int Power
		{
			get
			{
				return this._Power;
			}
			set
			{
				if ((this._Power != value))
				{
					this.OnPowerChanging(value);
					this.SendPropertyChanging();
					this._Power = value;
					this.SendPropertyChanged("Power");
					this.OnPowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsInjured", DbType="Bit NOT NULL")]
		public bool IsInjured
		{
			get
			{
				return this._IsInjured;
			}
			set
			{
				if ((this._IsInjured != value))
				{
					this.OnIsInjuredChanging(value);
					this.SendPropertyChanging();
					this._IsInjured = value;
					this.SendPropertyChanged("IsInjured");
					this.OnIsInjuredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Team_SoccerPlayer", Storage="_Team", ThisKey="TeamID", OtherKey="TeamID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Team Team
		{
			get
			{
				return this._Team.Entity;
			}
			set
			{
				Team previousValue = this._Team.Entity;
				if (((previousValue != value) 
							|| (this._Team.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Team.Entity = null;
						previousValue.SoccerPlayers.Remove(this);
					}
					this._Team.Entity = value;
					if ((value != null))
					{
						value.SoccerPlayers.Add(this);
						this._TeamID = value.TeamID;
					}
					else
					{
						this._TeamID = default(int);
					}
					this.SendPropertyChanged("Team");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SpecialTrainingDefinitions")]
	public partial class SpecialTrainingDefinition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SpecialTrainingDefinitionID;
		
		private string _Name;
		
		private string _Description;
		
		private int _RequiredXP;
		
		private int _EnergyStep;
		
		private int _EnergyTotal;
		
		private EntitySet<SpecialTraining> _SpecialTrainings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSpecialTrainingDefinitionIDChanging(int value);
    partial void OnSpecialTrainingDefinitionIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnRequiredXPChanging(int value);
    partial void OnRequiredXPChanged();
    partial void OnEnergyStepChanging(int value);
    partial void OnEnergyStepChanged();
    partial void OnEnergyTotalChanging(int value);
    partial void OnEnergyTotalChanged();
    #endregion
		
		public SpecialTrainingDefinition()
		{
			this._SpecialTrainings = new EntitySet<SpecialTraining>(new Action<SpecialTraining>(this.attach_SpecialTrainings), new Action<SpecialTraining>(this.detach_SpecialTrainings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialTrainingDefinitionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SpecialTrainingDefinitionID
		{
			get
			{
				return this._SpecialTrainingDefinitionID;
			}
			set
			{
				if ((this._SpecialTrainingDefinitionID != value))
				{
					this.OnSpecialTrainingDefinitionIDChanging(value);
					this.SendPropertyChanging();
					this._SpecialTrainingDefinitionID = value;
					this.SendPropertyChanged("SpecialTrainingDefinitionID");
					this.OnSpecialTrainingDefinitionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequiredXP", DbType="Int NOT NULL")]
		public int RequiredXP
		{
			get
			{
				return this._RequiredXP;
			}
			set
			{
				if ((this._RequiredXP != value))
				{
					this.OnRequiredXPChanging(value);
					this.SendPropertyChanging();
					this._RequiredXP = value;
					this.SendPropertyChanged("RequiredXP");
					this.OnRequiredXPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnergyStep", DbType="Int NOT NULL")]
		public int EnergyStep
		{
			get
			{
				return this._EnergyStep;
			}
			set
			{
				if ((this._EnergyStep != value))
				{
					this.OnEnergyStepChanging(value);
					this.SendPropertyChanging();
					this._EnergyStep = value;
					this.SendPropertyChanged("EnergyStep");
					this.OnEnergyStepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnergyTotal", DbType="Int NOT NULL")]
		public int EnergyTotal
		{
			get
			{
				return this._EnergyTotal;
			}
			set
			{
				if ((this._EnergyTotal != value))
				{
					this.OnEnergyTotalChanging(value);
					this.SendPropertyChanging();
					this._EnergyTotal = value;
					this.SendPropertyChanged("EnergyTotal");
					this.OnEnergyTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SpecialTrainingDefinition_SpecialTraining", Storage="_SpecialTrainings", ThisKey="SpecialTrainingDefinitionID", OtherKey="SpecialTrainingDefinitionID")]
		public EntitySet<SpecialTraining> SpecialTrainings
		{
			get
			{
				return this._SpecialTrainings;
			}
			set
			{
				this._SpecialTrainings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SpecialTrainings(SpecialTraining entity)
		{
			this.SendPropertyChanging();
			entity.SpecialTrainingDefinition = this;
		}
		
		private void detach_SpecialTrainings(SpecialTraining entity)
		{
			this.SendPropertyChanging();
			entity.SpecialTrainingDefinition = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SpecialTrainings")]
	public partial class SpecialTraining : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SpecialTrainingID;
		
		private int _TeamID;
		
		private int _SpecialTrainingDefinitionID;
		
		private int _EnergyCurrent;
		
		private bool _IsCompleted;
		
		private EntityRef<SpecialTrainingDefinition> _SpecialTrainingDefinition;
		
		private EntityRef<Team> _Team;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSpecialTrainingIDChanging(int value);
    partial void OnSpecialTrainingIDChanged();
    partial void OnTeamIDChanging(int value);
    partial void OnTeamIDChanged();
    partial void OnSpecialTrainingDefinitionIDChanging(int value);
    partial void OnSpecialTrainingDefinitionIDChanged();
    partial void OnEnergyCurrentChanging(int value);
    partial void OnEnergyCurrentChanged();
    partial void OnIsCompletedChanging(bool value);
    partial void OnIsCompletedChanged();
    #endregion
		
		public SpecialTraining()
		{
			this._SpecialTrainingDefinition = default(EntityRef<SpecialTrainingDefinition>);
			this._Team = default(EntityRef<Team>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialTrainingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SpecialTrainingID
		{
			get
			{
				return this._SpecialTrainingID;
			}
			set
			{
				if ((this._SpecialTrainingID != value))
				{
					this.OnSpecialTrainingIDChanging(value);
					this.SendPropertyChanging();
					this._SpecialTrainingID = value;
					this.SendPropertyChanged("SpecialTrainingID");
					this.OnSpecialTrainingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamID", DbType="Int NOT NULL")]
		public int TeamID
		{
			get
			{
				return this._TeamID;
			}
			set
			{
				if ((this._TeamID != value))
				{
					if (this._Team.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTeamIDChanging(value);
					this.SendPropertyChanging();
					this._TeamID = value;
					this.SendPropertyChanged("TeamID");
					this.OnTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialTrainingDefinitionID", DbType="Int NOT NULL")]
		public int SpecialTrainingDefinitionID
		{
			get
			{
				return this._SpecialTrainingDefinitionID;
			}
			set
			{
				if ((this._SpecialTrainingDefinitionID != value))
				{
					if (this._SpecialTrainingDefinition.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSpecialTrainingDefinitionIDChanging(value);
					this.SendPropertyChanging();
					this._SpecialTrainingDefinitionID = value;
					this.SendPropertyChanged("SpecialTrainingDefinitionID");
					this.OnSpecialTrainingDefinitionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnergyCurrent", DbType="Int NOT NULL")]
		public int EnergyCurrent
		{
			get
			{
				return this._EnergyCurrent;
			}
			set
			{
				if ((this._EnergyCurrent != value))
				{
					this.OnEnergyCurrentChanging(value);
					this.SendPropertyChanging();
					this._EnergyCurrent = value;
					this.SendPropertyChanged("EnergyCurrent");
					this.OnEnergyCurrentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCompleted", DbType="Bit NOT NULL")]
		public bool IsCompleted
		{
			get
			{
				return this._IsCompleted;
			}
			set
			{
				if ((this._IsCompleted != value))
				{
					this.OnIsCompletedChanging(value);
					this.SendPropertyChanging();
					this._IsCompleted = value;
					this.SendPropertyChanged("IsCompleted");
					this.OnIsCompletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SpecialTrainingDefinition_SpecialTraining", Storage="_SpecialTrainingDefinition", ThisKey="SpecialTrainingDefinitionID", OtherKey="SpecialTrainingDefinitionID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public SpecialTrainingDefinition SpecialTrainingDefinition
		{
			get
			{
				return this._SpecialTrainingDefinition.Entity;
			}
			set
			{
				SpecialTrainingDefinition previousValue = this._SpecialTrainingDefinition.Entity;
				if (((previousValue != value) 
							|| (this._SpecialTrainingDefinition.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SpecialTrainingDefinition.Entity = null;
						previousValue.SpecialTrainings.Remove(this);
					}
					this._SpecialTrainingDefinition.Entity = value;
					if ((value != null))
					{
						value.SpecialTrainings.Add(this);
						this._SpecialTrainingDefinitionID = value.SpecialTrainingDefinitionID;
					}
					else
					{
						this._SpecialTrainingDefinitionID = default(int);
					}
					this.SendPropertyChanged("SpecialTrainingDefinition");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Team_SpecialTraining", Storage="_Team", ThisKey="TeamID", OtherKey="TeamID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Team Team
		{
			get
			{
				return this._Team.Entity;
			}
			set
			{
				Team previousValue = this._Team.Entity;
				if (((previousValue != value) 
							|| (this._Team.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Team.Entity = null;
						previousValue.SpecialTrainings.Remove(this);
					}
					this._Team.Entity = value;
					if ((value != null))
					{
						value.SpecialTrainings.Add(this);
						this._TeamID = value.TeamID;
					}
					else
					{
						this._TeamID = default(int);
					}
					this.SendPropertyChanged("Team");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teams")]
	public partial class Team : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TeamID;
		
		private int _PredefinedTeamID;
		
		private string _Name;
		
		private string _Formation;
		
		private int _TrueSkill;
		
		private int _XP;
		
		private int _SkillPoints;
		
		private int _Energy;
		
		private int _Fitness;
		
		private double _Mean;
		
		private double _StandardDeviation;
		
		private EntitySet<MatchParticipation> _MatchParticipations;
		
		private EntityRef<PendingTraining> _PendingTraining;
		
		private EntitySet<SoccerPlayer> _SoccerPlayers;
		
		private EntitySet<SpecialTraining> _SpecialTrainings;
		
		private EntityRef<Player> _Player;
		
		private EntityRef<PredefinedTeam> _PredefinedTeam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeamIDChanging(int value);
    partial void OnTeamIDChanged();
    partial void OnPredefinedTeamIDChanging(int value);
    partial void OnPredefinedTeamIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFormationChanging(string value);
    partial void OnFormationChanged();
    partial void OnTrueSkillChanging(int value);
    partial void OnTrueSkillChanged();
    partial void OnXPChanging(int value);
    partial void OnXPChanged();
    partial void OnSkillPointsChanging(int value);
    partial void OnSkillPointsChanged();
    partial void OnEnergyChanging(int value);
    partial void OnEnergyChanged();
    partial void OnFitnessChanging(int value);
    partial void OnFitnessChanged();
    partial void OnMeanChanging(double value);
    partial void OnMeanChanged();
    partial void OnStandardDeviationChanging(double value);
    partial void OnStandardDeviationChanged();
    #endregion
		
		public Team()
		{
			this._MatchParticipations = new EntitySet<MatchParticipation>(new Action<MatchParticipation>(this.attach_MatchParticipations), new Action<MatchParticipation>(this.detach_MatchParticipations));
			this._PendingTraining = default(EntityRef<PendingTraining>);
			this._SoccerPlayers = new EntitySet<SoccerPlayer>(new Action<SoccerPlayer>(this.attach_SoccerPlayers), new Action<SoccerPlayer>(this.detach_SoccerPlayers));
			this._SpecialTrainings = new EntitySet<SpecialTraining>(new Action<SpecialTraining>(this.attach_SpecialTrainings), new Action<SpecialTraining>(this.detach_SpecialTrainings));
			this._Player = default(EntityRef<Player>);
			this._PredefinedTeam = default(EntityRef<PredefinedTeam>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TeamID
		{
			get
			{
				return this._TeamID;
			}
			set
			{
				if ((this._TeamID != value))
				{
					if (this._Player.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTeamIDChanging(value);
					this.SendPropertyChanging();
					this._TeamID = value;
					this.SendPropertyChanged("TeamID");
					this.OnTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PredefinedTeamID", DbType="Int NOT NULL")]
		public int PredefinedTeamID
		{
			get
			{
				return this._PredefinedTeamID;
			}
			set
			{
				if ((this._PredefinedTeamID != value))
				{
					if (this._PredefinedTeam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPredefinedTeamIDChanging(value);
					this.SendPropertyChanging();
					this._PredefinedTeamID = value;
					this.SendPropertyChanged("PredefinedTeamID");
					this.OnPredefinedTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Formation", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Formation
		{
			get
			{
				return this._Formation;
			}
			set
			{
				if ((this._Formation != value))
				{
					this.OnFormationChanging(value);
					this.SendPropertyChanging();
					this._Formation = value;
					this.SendPropertyChanged("Formation");
					this.OnFormationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrueSkill", DbType="Int NOT NULL")]
		public int TrueSkill
		{
			get
			{
				return this._TrueSkill;
			}
			set
			{
				if ((this._TrueSkill != value))
				{
					this.OnTrueSkillChanging(value);
					this.SendPropertyChanging();
					this._TrueSkill = value;
					this.SendPropertyChanged("TrueSkill");
					this.OnTrueSkillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XP", DbType="Int NOT NULL")]
		public int XP
		{
			get
			{
				return this._XP;
			}
			set
			{
				if ((this._XP != value))
				{
					this.OnXPChanging(value);
					this.SendPropertyChanging();
					this._XP = value;
					this.SendPropertyChanged("XP");
					this.OnXPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkillPoints", DbType="Int NOT NULL")]
		public int SkillPoints
		{
			get
			{
				return this._SkillPoints;
			}
			set
			{
				if ((this._SkillPoints != value))
				{
					this.OnSkillPointsChanging(value);
					this.SendPropertyChanging();
					this._SkillPoints = value;
					this.SendPropertyChanged("SkillPoints");
					this.OnSkillPointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Energy", DbType="Int NOT NULL")]
		public int Energy
		{
			get
			{
				return this._Energy;
			}
			set
			{
				if ((this._Energy != value))
				{
					this.OnEnergyChanging(value);
					this.SendPropertyChanging();
					this._Energy = value;
					this.SendPropertyChanged("Energy");
					this.OnEnergyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fitness", DbType="Int NOT NULL")]
		public int Fitness
		{
			get
			{
				return this._Fitness;
			}
			set
			{
				if ((this._Fitness != value))
				{
					this.OnFitnessChanging(value);
					this.SendPropertyChanging();
					this._Fitness = value;
					this.SendPropertyChanged("Fitness");
					this.OnFitnessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mean", DbType="Float NOT NULL")]
		public double Mean
		{
			get
			{
				return this._Mean;
			}
			set
			{
				if ((this._Mean != value))
				{
					this.OnMeanChanging(value);
					this.SendPropertyChanging();
					this._Mean = value;
					this.SendPropertyChanged("Mean");
					this.OnMeanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardDeviation", DbType="Float NOT NULL")]
		public double StandardDeviation
		{
			get
			{
				return this._StandardDeviation;
			}
			set
			{
				if ((this._StandardDeviation != value))
				{
					this.OnStandardDeviationChanging(value);
					this.SendPropertyChanging();
					this._StandardDeviation = value;
					this.SendPropertyChanged("StandardDeviation");
					this.OnStandardDeviationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Team_MatchParticipation", Storage="_MatchParticipations", ThisKey="TeamID", OtherKey="TeamID")]
		public EntitySet<MatchParticipation> MatchParticipations
		{
			get
			{
				return this._MatchParticipations;
			}
			set
			{
				this._MatchParticipations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Team_PendingTraining", Storage="_PendingTraining", ThisKey="TeamID", OtherKey="TeamID", IsUnique=true, IsForeignKey=false)]
		public PendingTraining PendingTraining
		{
			get
			{
				return this._PendingTraining.Entity;
			}
			set
			{
				PendingTraining previousValue = this._PendingTraining.Entity;
				if (((previousValue != value) 
							|| (this._PendingTraining.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PendingTraining.Entity = null;
						previousValue.Team = null;
					}
					this._PendingTraining.Entity = value;
					if ((value != null))
					{
						value.Team = this;
					}
					this.SendPropertyChanged("PendingTraining");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Team_SoccerPlayer", Storage="_SoccerPlayers", ThisKey="TeamID", OtherKey="TeamID")]
		public EntitySet<SoccerPlayer> SoccerPlayers
		{
			get
			{
				return this._SoccerPlayers;
			}
			set
			{
				this._SoccerPlayers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Team_SpecialTraining", Storage="_SpecialTrainings", ThisKey="TeamID", OtherKey="TeamID")]
		public EntitySet<SpecialTraining> SpecialTrainings
		{
			get
			{
				return this._SpecialTrainings;
			}
			set
			{
				this._SpecialTrainings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Player_Team", Storage="_Player", ThisKey="TeamID", OtherKey="PlayerID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Player Player
		{
			get
			{
				return this._Player.Entity;
			}
			set
			{
				Player previousValue = this._Player.Entity;
				if (((previousValue != value) 
							|| (this._Player.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Player.Entity = null;
						previousValue.Team = null;
					}
					this._Player.Entity = value;
					if ((value != null))
					{
						value.Team = this;
						this._TeamID = value.PlayerID;
					}
					else
					{
						this._TeamID = default(int);
					}
					this.SendPropertyChanged("Player");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PredefinedTeam_Team", Storage="_PredefinedTeam", ThisKey="PredefinedTeamID", OtherKey="PredefinedTeamID", IsForeignKey=true)]
		public PredefinedTeam PredefinedTeam
		{
			get
			{
				return this._PredefinedTeam.Entity;
			}
			set
			{
				PredefinedTeam previousValue = this._PredefinedTeam.Entity;
				if (((previousValue != value) 
							|| (this._PredefinedTeam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PredefinedTeam.Entity = null;
						previousValue.Teams.Remove(this);
					}
					this._PredefinedTeam.Entity = value;
					if ((value != null))
					{
						value.Teams.Add(this);
						this._PredefinedTeamID = value.PredefinedTeamID;
					}
					else
					{
						this._PredefinedTeamID = default(int);
					}
					this.SendPropertyChanged("PredefinedTeam");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MatchParticipations(MatchParticipation entity)
		{
			this.SendPropertyChanging();
			entity.Team = this;
		}
		
		private void detach_MatchParticipations(MatchParticipation entity)
		{
			this.SendPropertyChanging();
			entity.Team = null;
		}
		
		private void attach_SoccerPlayers(SoccerPlayer entity)
		{
			this.SendPropertyChanging();
			entity.Team = this;
		}
		
		private void detach_SoccerPlayers(SoccerPlayer entity)
		{
			this.SendPropertyChanging();
			entity.Team = null;
		}
		
		private void attach_SpecialTrainings(SpecialTraining entity)
		{
			this.SendPropertyChanging();
			entity.Team = this;
		}
		
		private void detach_SpecialTrainings(SpecialTraining entity)
		{
			this.SendPropertyChanging();
			entity.Team = null;
		}
	}
}
#pragma warning restore 1591
